moira-kotlin-client movement to github
yoomoney/moira-kotlin-client pull request #1
Opened 2021-09-13 21:42 UTC by karpenkovk

2021-09-14 05:36 UTC, f0y requested changes

2021-09-14 05:36 UTC, f0y commented on CHANGELOG.md
> +* Изменения связанные с переходом на github
На английском пжл

2021-09-14 05:36 UTC, f0y commented
Добавь пжл файл CODEOWNERS

2021-09-14 19:17 UTC, layfe requested changes

2021-09-14 19:17 UTC, layfe commented on project.gradle
> +        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50'
здесь можно внешний не подключать, сделать apply нашего 
apply plugin: 'ru.yoomoney.gradle.plugins.kotlin-plugin'
пример можно посмотреть в компонентах где есть тесты на kotlin

2021-09-14 19:17 UTC, layfe commented on dependencies.gradle
> +    compile 'org.jetbrains.kotlin:kotlin-stdlib:1.3.50'
тогда и это уйдет

2021-09-14 21:49 UTC, karpenkovk commented on CHANGELOG.md
> +* Изменения связанные с переходом на github
fixed

2021-09-14 21:49 UTC, karpenkovk commented on project.gradle
> +        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50'
подключил наш плагин kotlin-plugin

2021-09-14 21:50 UTC, karpenkovk commented on dependencies.gradle
> +    compile 'org.jetbrains.kotlin:kotlin-stdlib:1.3.50'
зависимости kotlin-stdlib и kotlin-script-runtime убрал

2021-09-15 12:08 UTC, f0y approved these changes

2021-09-15 12:12 UTC, layfe approved these changes

2021-09-15 12:13 UTC, merged